### PR TITLE
Start of P2 Group

### PR DESCRIPTION
**Pull request by DarthHater**
Scaffolding to start P2 Group

This pull request makes the following changes:
* Abstract some P2 Recipe stuff into a `P2RecipeSupport` class
* Add `P2GroupRecipe`
* Add `P2Group.js`

### CODE REVIEW

**Comment by simonmiller99** [comment]
hi - did you add me as a collaborator on this branch?  My manager very enthusiastic about what we can achieve if we can expand the role of our buildserver/repo all in one by adding handlers and creating our own.

**Comment by laeubi** [comment]
Just wondering: Is this about MERGING different P2 repos into one, or supporting COMPOSITE ones?
IMO merging can be done easier with a (generated) composite repository instead of really merging the artifacts.

**Comment by simonmiller99** [comment]
Christoph, right now I don’t know as I’m just finding my way. I need to support a handful of p2 sites and abstract the grim reality away from users by giving them one local portal link. I’m totally open to suggestions about optimal methods

Sent from my iPhone

On 26 Oct 2018, at 09:17, Christoph Läubrich <notifications@github.com<mailto:notifications@github.com>> wrote:


Just wondering: Is this about MERGING different P2 repos into one, or supporting COMPOSITE ones?
IMO merging can be done easier with a (generated) composite repository instead of really merging the artifacts.

**Comment by simonmiller99** [comment]
> Just wondering: Is this about MERGING different P2 repos into one, or supporting COMPOSITE ones?
> IMO merging can be done easier with a (generated) composite repository instead of really merging the artifacts.

but ANY advice or guidance gratefullly accepted

**Comment by laeubi** [comment]
You can read about composite repositories here: https://wiki.eclipse.org/Equinox/p2/Composite_Repositories_(new) so if you have two repos that should be accessing using one url you can create a new composite and reference these both urls in them.
Of course, one can also mirror them and won't need use the original url, but it makes it much easier since you don't need to modify the original repo.

**Comment by simonmiller99** [comment]
Thank you

Sent from my iPhone

On 7 Nov 2018, at 08:46, Christoph Läubrich <notifications@github.com<mailto:notifications@github.com>> wrote:


You can read about composite repositories here: https://wiki.eclipse.org/Equinox/p2/Composite_Repositories_(new) so if you have two repos that should be accessing using one url you can create a new composite and reference these both urls in them.
Of course, one can also mirror them and won't need use the original url, but it makes it much easier since you don't need to modify the original repo.

**Comment by tihefrequi** [comment]
How can i help to finish this feature?

**Comment by simonmiller99** [comment]
hi - I was working on this, and I have ideas on how to do it. I've been given another long running docker project and have to put P2 aside for now.

Simon

________________________________

**Comment by proteus1121** [comment]
Closed, because p2 moved in Nexus Repository Manager, work will continue in [nexus-public](https://github.com/sonatype/nexus-public), more: https://github.com/sonatype-nexus-community/nexus-repository-p2/pull/79

**Pull request closed without merging**
